universe = vanilla

executable = scripts/prepare_inputs.sh

log    = scripts/condor_logs/prepare_inputs.$(Cluster).log
output = scripts/condor_logs/prepare_inputs.$(Cluster).$(Process).out
error  = scripts/condor_logs/prepare_inputs.$(Cluster).$(Process).err

getenv = True
transfer_input_files = DisplacedVertex_splitter.py, DisplacedVertex_preproc.py, dv_converter_utils.py

environment = "REPO_DIR=$(SUBMIT_DIR)"

request_cpus = 4
request_memory = 32 GB
request_disk = 10 GB

+JobFlavour = "workday"

queue 1
